[package]
name = "orx-iterable"
version = "2.8.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "TODO"
license = "MIT"
repository = "https://github.com/orxfun/orx-iterable/"
keywords = ["vec", "pinned", "bag", "container", "split"]
categories = ["data-structures", "rust-patterns", "no-std"]

[dependencies]
orx-closure = { version = "0.1.4", registry = "artifactory" }
orx-exclusive = { path = "../orx-exclusive" }
