mod chained;
mod cloned;
mod cloning_iter;
mod copied;
mod filter_mapped;
mod filtered;
mod flat_mapped;
mod flattened;
mod mapped;
mod mapped_while;
mod skipped;
mod taken;
mod taken_while;
// mod owning_iterable;
mod zipped;

pub use chained::{Chained, IntoChained};
pub use cloned::{Cloned, IntoCloned};
pub use cloning_iter::{CloningIterable, IntoCloningIterable};
pub use copied::{Copied, IntoCopied};
pub use filtered::{Filtered, FilteredIter, IntoFiltered};
pub use flattened::{Flattened, FlattenedIter, IntoFlattened};
pub use mapped::{IntoMapped, Mapped, MappedIter};
// pub use owning_iterable::{IntoOwningIterable, OwningIterable};
pub use flat_mapped::{FlatMapped, FlatMappedIter, IntoFlatMapped};
pub use mapped_while::{IntoMappedWhileIterable, MappedWhile, MappedWhileIter};
pub use skipped::{IntoSkipped, Skipped};
pub use taken::{IntoTaken, Taken};
pub use taken_while::{IntoTakenWhile, TakenWhile};
pub use zipped::{IntoZipped, Zipped};
